name: Build lit-new

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup node'
        uses: actions/setup-node@v1
      - name: 'Install NPM dependencies'
        run: npm install
      - name: 'Build election-vue'
        run: npm run build      
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
