name: Macos Builder

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Setup node'
        uses: actions/setup-node@v1
      - name: 'Install NPM dependencies'
        run: npm install
      - run: npm install electron-builder@latest -D
      - name: 'Build LitNews'
        run: npm run build      
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
